/**
 * Standalone quote collection. Kept out of any route module so lightweight
 * screens (like the splash) can use it without pulling in a whole page's
 * dependency graph.
 */
export const quotes: string[] = [
  "The last bench isn't a seating arrangement; it's a mindset. Prove them wrong.",
  "Your excuses sound best to the mind that is making them up. Stop listening.",
  "I know recovery is hard but believe me regret is even harder. So choose wisely.",
  "Don't stop when you're tired. Stop when you are done.",
  "Regret of neglected opportunity is the worst hell a living soul can inhabit.",
  "An amateur waits for motivation. A last-bench legend relies on absolute discipline.",
  "When you feel like quitting, remember why you started this grueling journey.",
  "Comfort is the silent killer of all your grand potential. Choose the struggle.",
  "Every drop of sweat today saves a tear of regret when results are announced.",
  "You've failed a thousand times before. Get back up and try one more time.",
  "Your alarm doesn't care how tired you are. Get out of bed and execute.",
  "Don't let your weak, quitting mind cheat you out of another victorious day.",
  "They expect you to fail. Disappoint them with your relentless work ethic.",
  "The textbook doesn't read itself. Flip the page and finish the chapter now.",
  "Small daily wins stack up to massive victories over 365 days. Keep pushing.",
  "Pain is temporary. A terrible rank card lasts forever. Choose your struggle wisely.",
  "No one is coming to save you. You have to climb out of this hole yourself.",
  "Your competition is studying right now while you scroll. Wake up.",
  "Consistency beats raw talent every single day of the week. Stay on it.",
  "Be obsessed with your personal growth, or stay completely ordinary.",
  "The secret of getting ahead is simply starting. Focus on the next 10 minutes.",
  "Legends aren't born in the spotlight; they are forged in the quiet dark.",
  "If it were easy, everyone would do it. That is why it belongs to you.",
  "Your future self is either thanking you or cursing you right now.",
  "Stop talking about what you want to do, and start showing the results.",
  "Discipline means doing what needs to be done, even when you hate it.",
  "You don't need a perfect plan; you just need to work harder than yesterday.",
  "The hours you put in when no one is watching are the ones that define you.",
  "Break the bad habits before they completely break your life goals.",
  "Another day is ending. Will you count this as a massive win or a lazy loss?",
  "No excuses, no shortcuts, no compromises. Just pure, unadulterated execution.",
  "The only bad study session is the one that you completely skipped.",
  "Suffer the pain of discipline today, or suffer the pain of regret tomorrow.",
  "They mock the backbenchers until the backbenchers clear the toughest exams.",
  "You are entirely capable of changing your life trajectory starting this second.",
  "Every temptation you resist builds another layer of your sovereign shield.",
  "Your mind will give up a thousand times before your body actually does. Override it.",
  "Success isn't given; it is earned on the battlefield of daily repetition.",
  "Focus on the process, not the mountain. Just win the current hour.",
  "Sleep is sweet, but ultimate victory is sweeter. Throw off the blanket.",
];
